#!/bin/sh
#
# genconfig - creates an OpenWrt config file for oldconfig
# Copyright (C) 2012  Philipp Psurek <phip@vmail.me>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.

version(){
echo "genconfig Version 0.0.20120502"

cat << EOF
Copyright © 2012 Philipp Psurek <phip@vmail.me>
            2012 Freifunk Rheinland <http://www.freifunk-rheinland.net/>

Lizenz GPLv3+: GNU GPL Version 3 oder höher <http://gnu.org/licenses/gpl.html>
Dies ist freie Software: Sie können sie ändern und weitergeben.
Es gibt keinerlei Garantien, soweit wie es das Gesetz erlaubt.
EOF
}

usage(){
cat << EOF
Aufruf: genconfig <flavour>
        genconfig [-h|-v]

Flavour:
# D-Link 
  dir300            DIR-300
# Linksys
  wrt54g            WTR54G <V4, WTR54GL
# TP-LINK
  tplite            TL-WR741ND, TL-WR841ND, TL-WR941ND, …
  tpusb             TL-WR1043ND, TL-WR2543ND, …
  tp                all

Optionen:
  -h, --help        Hilfe
  -v, --version     Version
EOF
}

# cat .config | grep -v -e "^#"
# while true; do echo; done | make oldconfig >/dev/null

# ar71xx
target_ar71xx(){
cat << EOF
CONFIG_TARGET_ar71xx=y
CONFIG_TARGET_ar71xx_generic=y
CONFIG_TARGET_ar71xx_generic_Default=y
CONFIG_HAS_SUBTARGETS=y
CONFIG_TARGET_BOARD="ar71xx"
CONFIG_TARGET_ARCH_PACKAGES="ar71xx"
EOF
}

# DIR-300
target_atheros(){
cat << EOF
CONFIG_TARGET_atheros=y
CONFIG_TARGET_atheros_Default=y
CONFIG_TARGET_BOARD="atheros"
CONFIG_TARGET_ARCH_PACKAGES="atheros"

CONFIG_PACKAGE_kmod-ath5k=y
# CONFIG_PACKAGE_kmod-cfg80211 is not set

CONFIG_MADWIFI_SINGLE_MODULE=y
CONFIG_MADWIFI_RCA_MINSTREL=y

# CONFIG_MADWIFI_RCA_SAMPLERATE is not set

# CONFIG_PACKAGE_kmod-mac80211-hwsim is not set
# CONFIG_PACKAGE_kmod-madwifi is not set

# CONFIG_MADWIFI_COMPRESSION is not set

CONFIG_PACKAGE_kmod-madwifi=y
# CONFIG_PACKAGE_kmod-mac80211 is not set
# CONFIG_PACKAGE_kmod-mac80211-hwsim is not set



CONFIG_BUSYBOX_CONFIG_FEATURE_HAVE_RPC=y

EOF
}


target_brcm47xx(){
cat << EOF
CONFIG_TARGET_brcm47xx=y
CONFIG_TARGET_brcm47xx_Broadcom-b43=y
CONFIG_TARGET_BOARD="brcm47xx"
CONFIG_TARGET_ARCH_PACKAGES="brcm47xx"

CONFIG_DEFAULT_kmod-b43=y
CONFIG_DEFAULT_kmod-b43legacy=y
CONFIG_DEFAULT_kmod-diag=y
CONFIG_DEFAULT_kmod-switch=y
CONFIG_DEFAULT_nvram=y

CONFIG_PCMCIA_SUPPORT=y

CONFIG_PACKAGE_nvram=y
CONFIG_PACKAGE_kmod-diag=y
CONFIG_PACKAGE_kmod-switch=y
CONFIG_PACKAGE_kmod-b43=y

CONFIG_B43_FW_5_100_138=y
CONFIG_B43_FW_SQUASH=y
CONFIG_B43_FW_SQUASH_COREREVS="5,6,7,8,9,10,11,13,14,15,16"
CONFIG_B43_FW_SQUASH_PHYTYPES="G,LP,N"
CONFIG_PACKAGE_B43_PHY_N=y
# CONFIG_PACKAGE_kmod-b43legacy is not set

CONFIG_B43LEGACY_FW_SQUASH=y
CONFIG_B43LEGACY_FW_SQUASH_COREREVS="1,2,3,4"
EOF
}

# Konfiguration für alle FF-Knoten
default(){
cat << EOF
# CONFIG_TARGET_ROOTFS_INITRAMFS is not set
# CONFIG_TARGET_ROOTFS_CPIOGZ is not set
CONFIG_TARGET_ROOTFS_TARGZ=y
# CONFIG_TARGET_ROOTFS_EXT4FS is not set
# CONFIG_TARGET_ROOTFS_JFFS2 is not set
CONFIG_TARGET_ROOTFS_SQUASHFS=y
CONFIG_TARGET_ROOTFS_DIR=""

CONFIG_IPV6=y

CONFIG_PACKAGE_dropbear=y
CONFIG_PACKAGE_hotplug2=y
CONFIG_PACKAGE_libc=y
CONFIG_PACKAGE_libgcc=y
CONFIG_PACKAGE_libpthread=y
CONFIG_PACKAGE_mtd=y
CONFIG_PACKAGE_opkg=y
CONFIG_PACKAGE_swconfig=y
CONFIG_PACKAGE_uci=y
CONFIG_PACKAGE_wireless-tools=y

CONFIG_PACKAGE_luci-lib-core_source=y
CONFIG_PACKAGE_luci-lib-nixio_notls=y

CONFIG_PACKAGE_kmod-batman-adv=y
CONFIG_KMOD_BATMAN_ADV_DEBUG_LOG=y
CONFIG_KMOD_BATMAN_ADV_BATCTL=y

CONFIG_PACKAGE_kmod-bonding=m
CONFIG_PACKAGE_kmod-ipv6=y
CONFIG_PACKAGE_kmod-ppp=m
CONFIG_PACKAGE_kmod-pppoe=m

CONFIG_PACKAGE_ppp=m
CONFIG_PACKAGE_ppp-mod-pppoe=m

CONFIG_PACKAGE_wpad-mini=y

CONFIG_PACKAGE_libuci=y

CONFIG_PACKAGE_flock=y

CONFIG_BUSYBOX_CONFIG_ASH_RANDOM_SUPPORT=y
EOF
}


packages_firewall(){
cat << EOF
CONFIG_PACKAGE_firewall=
CONFIG_PACKAGE_librt=
CONFIG_PACKAGE_ip6tables=
CONFIG_PACKAGE_kmod-ledtrig-netfilter=
CONFIG_PACKAGE_kmod-lib-crc-ccitt=
CONFIG_PACKAGE_kmod-lib-textsearch=
CONFIG_PACKAGE_kmod-ip6tables=
CONFIG_PACKAGE_kmod-ipt-core=
CONFIG_PACKAGE_kmod-ipt-compat-xtables=
CONFIG_PACKAGE_kmod-ipt-conntrack=
CONFIG_PACKAGE_kmod-ipt-conntrack-extra=
CONFIG_PACKAGE_kmod-ipt-filter=
CONFIG_PACKAGE_kmod-ipt-ipp2p=
CONFIG_PACKAGE_kmod-ipt-nat=
CONFIG_PACKAGE_kmod-ipt-nat-extra=
CONFIG_PACKAGE_kmod-ipt-nathelper=

CONFIG_PACKAGE_iptables=
CONFIG_PACKAGE_iptables-mod-conntrack-extra=
CONFIG_PACKAGE_iptables-mod-filter=
CONFIG_PACKAGE_iptables-mod-ipp2p=
CONFIG_PACKAGE_iptables-mod-nat-extra=
CONFIG_PACKAGE_l7-protocols=

CONFIG_PACKAGE_libip4tc=
CONFIG_PACKAGE_libip6tc=
CONFIG_PACKAGE_libxtables=
EOF
}

packages_dhcp(){
cat << EOF
CONFIG_PACKAGE_dnsmasq=
CONFIG_PACKAGE_wide-dhcpv6-server=
CONFIG_PACKAGE_radvd=
EOF
}


packages_n2n(){
cat << EOF
CONFIG_PACKAGE_kmod-tun=
CONFIG_PACKAGE_n2n=
EOF
}

packages_openvpn(){
cat << EOF
CONFIG_PACKAGE_openvpn=
CONFIG_OPENVPN_DISABLE_EUREPHIA=y
CONFIG_OPENVPN_DISABLE_MANAGEMENT=y
CONFIG_OPENVPN_ENABLE_PASSWORD_SAVE=y

EOF
}

packages_usb(){
cat << EOF
CONFIG_PACKAGE_kmod-ledtrig-usbdev=
CONFIG_PACKAGE_kmod-usb-ohci=
CONFIG_PACKAGE_kmod-usb2=
EOF
}

packages_switch(){
cat << EOF
CONFIG_PACKAGE_kmod-libphy=
CONFIG_PACKAGE_kmod-swconfig=
CONFIG_PACKAGE_kmod-switch-rtl8366-smi=
CONFIG_PACKAGE_kmod-switch-rtl8366rb=
EOF
}

packages_webserver(){
cat << EOF
CONFIG_PACKAGE_uhttpd=
EOF
}

packages_util(){
cat << EOF
CONFIG_PACKAGE_iputils-ping=
CONFIG_PACKAGE_iputils-ping6=
CONFIG_PACKAGE_iputils-tracepath=
CONFIG_PACKAGE_iputils-tracepath6=
CONFIG_PACKAGE_iputils-traceroute6=

CONFIG_PACKAGE_nano=

CONFIG_PACKAGE_iperf=
CONFIG_PACKAGE_iperf-mt=
EOF
}

packages_unknown(){
cat << EOF
CONFIG_PACKAGE_kmod-button-hotplug=
CONFIG_PACKAGE_kmod-input-gpio-keys-polled=
CONFIG_PACKAGE_kmod-input-polldev=
EOF
}

packages_ffrl(){
cat << EOF
CONFIG_PACKAGE_udp-broadcast=
# CONFIG_PACKAGE_ffrl-fsm is not set
CONFIG_PACKAGE_ffrl-miniconfig=
EOF
}

gen_config(){
if [ "$case" = "tp" ] || [ "$case" = "ar71xx" ]; then
target_ar71xx
default
packages_firewall  | sed -e "s/=$/=y/g"
packages_dhcp      | sed -e "s/=$/=y/g"
packages_n2n       | sed -e "s/=$/=y/g"
packages_openvpn   | sed -e "s/=$/=y/g"
packages_usb       | sed -e "s/=$/=y/g"
packages_switch    | sed -e "s/=$/=m/g"
packages_webserver | sed -e "s/=$/=y/g"
packages_util      | sed -e "s/=$/=m/g"
packages_unknown   | sed -e "s/=$/=y/g"
packages_ffrl      | sed -e "s/=$/=y/g"
elif [ "$case" = "dir300" ] || [ "$case" = "atheros" ]; then
target_atheros
default
packages_firewall  | sed -e "s/=$/=m/g"
packages_dhcp      | sed -e "s/=$/=m/g"
packages_n2n       | sed -e "s/=$/=y/g"
packages_openvpn   | sed -e "s/=$/=m/g"
#packages_usb       | sed -e "s/=$/=m/g"
#packages_switch    | sed -e "s/=$/=m/g"
packages_webserver | sed -e "s/=$/=m/g"
packages_util      | sed -e "s/=$/=m/g"
#packages_unknown   | sed -e "s/=$/=m/g"
packages_ffrl      | sed -e "s/=$/=y/g"
elif [ "$case" = "wrt54g" ] || [ "$case" = "brcm47xx" ]; then
target_brcm47xx
default
packages_firewall  | sed -e "s/=$/=m/g"
packages_dhcp      | sed -e "s/=$/=m/g"
packages_n2n       | sed -e "s/=$/=y/g"
packages_openvpn   | sed -e "s/=$/=m/g"
#packages_usb       | sed -e "s/=$/=m/g"
#packages_switch    | sed -e "s/=$/=m/g"
packages_webserver | sed -e "s/=$/=m/g"
packages_util      | sed -e "s/=$/=m/g"
#packages_unknown   | sed -e "s/=$/=m/g"
packages_ffrl      | sed -e "s/=$/=y/g"
else
  echo "Ungültige Eingabe"
  exit 1
fi
}

# Eingabeverarbeitung
if [ "$1" != "" ]; then
  case=$1
  case "$case" in
  --help)
    usage
    exit 0
    ;;
  -h)
    usage
    exit 0
    ;;
  --version)
    version
    exit 0
    ;;
  -v)
    version
    exit 0
    ;;
  *)
    gen_config
    ;;
  esac
else
  usage
fi

