#!/bin/bash
#
# makepackages - stupid script for lazy people which compiles certain packages
# Copyright (C) 2012  Philipp Psurek <phip@vmail.me>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.

rootdir=$(pwd)

makepackage(){
  cd ${rootdir}/openwrt/trunk && make package/feeds/${feed}/${package}/compile
}

install_packages(){
  for feed in ffrlgit ffrl
  do
    cd ${rootdir}/openwrt/trunk && ./scripts/feeds update ${feed}
    for type in all arch
    do
      grep -v -e "^#" -e "^$" ${rootdir}/config/packages/${type} \
        | while read package feed; do
          cd ${rootdir}/openwrt/trunk
          [ ! -e ${rootdir}/openwrt/trunk/package/feeds/${feed} ] \
            && ./scripts/feeds install -p ${feed} ${package}
        done
    done
  done
}

read_packages(){
  grep -v -e "^#" -e "^$" ${rootdir}/config/packages/${type} \
  | while read package feed; do
    makepackage
    move_package
  done
}

openwrt_prepare(){
  cd ${rootdir}
  ./genconfig ${arch} > openwrt/trunk/.config
  cd ${rootdir}/openwrt/trunk && while true; do echo; done \
   | make oldconfig >/dev/null
}

move_package(){
[[ ! -d ${rootdir}/packages ]] && mkdir -p ${rootdir}/packages
mv ${rootdir}/openwrt/trunk/bin/${arch}/packages/${package}* ${rootdir}/packages/
}

arch=ar71xx
install_packages

arch=ar71xx
type=all
openwrt_prepare
read_packages

type=arch
for arch in ar71xx
#for arch in ar71xx atheros brcm47xx
do
  openwrt_prepare
  read_packages
done

