#!/bin/bash
#
# makepackages - stupid script for lazy people which compiles certain packages
# Original Copyright (C) 2012  Philipp Psurek <phip@vmail.me>
# Modified by Cyrus (Lcb01@Lcb01.de)
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.

rootdir=$(pwd)
feeds="ffadvgit ffadv"
targets="ar71xx"
config="all"

make_package(){
	local package=$1
	local feed=$2
	echo "Make package $package from feed $feed"
  cd ${rootdir}/openwrt/attitude_adjustment && make package/feeds/${feed}/${package}/compile
}

install_feeds(){
  for feed in $feeds
  do
	cat ${rootdir}/openwrt/attitude_adjustment/feeds.conf.default ${rootdir}/feeds.conf > ${rootdir}/openwrt/attitude_adjustment/feeds.conf
    cd ${rootdir}/openwrt/attitude_adjustment && ./scripts/feeds update ${feed}
    for type in $config
    do
      grep -v -e "^#" -e "^$" ${rootdir}/config/packages/${config} \
        | while read package feed; do
          cd ${rootdir}/openwrt/attitude_adjustment
          [ ! -e ${rootdir}/openwrt/attitude_adjustment/package/feeds/${feed} ] \
            && ./scripts/feeds install -p ${feed} ${package}
        done
    done
  done
}

build_packages(){
  local arch=$1
  echo "Building config file(s) $config for arch $arch"
  grep -v -e "^#" -e "^$" ${rootdir}/config/packages/${config} \
  | while read package feed; do
    make_package $package $feed
	move_package $package $arch
  done
}

generate_config(){
	local arch=$1
	cd ${rootdir}
	./genconfig ${arch} > openwrt/attitude_adjustment/.config
	cd ${rootdir}/openwrt/attitude_adjustment && while true; do echo; done \
	| make oldconfig >/dev/null
}

move_package(){
	local package=$1
	local arch=$2
	echo "Move package $package for arch $arch"
	[[ ! -d ${rootdir}/packages/${arch} ]] && mkdir -p ${rootdir}/packages/${arch}
	rm -f ${rootdir}/packages/${arch}/${package}*
	mv ${rootdir}/openwrt/attitude_adjustment/bin/${arch}/packages/${package}* ${rootdir}/packages/${arch}/
}

index_packages(){
        local arch=$1
        local pkg_dir=${rootdir}/packages/${arch}/
        cd $pkg_dir
        rm -f md5sums Packages Packages.gz
        md5sum  * > md5sums
        ${rootdir}/openwrt/attitude_adjustment/scripts/ipkg-make-index.sh . > Packages
        cat Packages | gzip > Packages.gz
        cd ${rootdir}
}

fail() {
    echo "$1" 1>&2
    exit 1
}

printArgs () {
    fail "Usage:
makepackage
build [config] : build packages
               If no config is supplied the 'all' 
               config will be used
build_index : build package index & md5sums

install_packages [config] : install packages from feeds
"
}

[ $# -lt 1 ] && printArgs
[ ! -e ${rootdir}/openwrt/attitude_adjustment/package/feeds/ffadvgit ] && install_feeds

case "$1" in
    build)
	[ $# -gt 1 ] && config=$2
	for arch in $targets
	do
		generate_config $arch
		build_packages $arch
		index_packages $arch
	done
	;;
	build_index)
	[ $# -gt 1 ] && config=$2
	for arch in $targets
		do
			index_packages $arch
		done
	;;
	install_packages)
	[ $# -gt 1 ] && config=$2
	install_feeds $config
	;;
    *)
	printArgs
esac

