#!/bin/sh
echo -en "Status: 200 OK\r\n"
echo -en "Content-Type: text/html\r\n"
echo -en "\r\n"
TEST=`cat `
TEST=`echo $TEST | sed 's/'target_url='/''/g'`
TEST=`/bin/urldecode "$TEST"`
TEST=`echo $TEST | sed 's/%2F/\//g'`
USER_MAC=`cat /proc/net/arp | grep $REMOTE_HOST | awk 'BEGIN { FS = " " } ; { print $4 }'`

. $IPKG_INSTROOT/etc/functions.sh
ISSPLASHED=0
config_load splash_users
is_mac() {
   config_get mac "$1" mac
   if [ "$mac" == "$USER_MAC" ]; then
   	ISSPLASHED=1
   fi
}
#check if user is alredy splashed
config_foreach is_mac user
sed 's/targeturl/'"$(echo $TEST| sed 's#/#\\/#g')"'/g' /www/iframe.html

if [ $ISSPLASHED -eq 1 ]; then
	exit
fi
#User is now free to go
iptables -t nat -I ffj_splash 1 -m mac --mac-source $USER_MAC -j ACCEPT > /dev/null

uci -q add splash_users user > /dev/null
uci -q set splash_users.@user[-1].mac=$USER_MAC > /dev/null
uci -q set splash_users.@user[-1].time=`date +%s` > /dev/null

exit 0


                                               

