#!/bin/sh -e
. $IPKG_INSTROOT/etc/functions.sh
. /etc/splash.sh

echo -en "Status: 200 OK\r\n"
echo -en "Content-Type: text/html\r\n"
echo -en "\r\n"

# decode request params
URL="http://$(sed 's/target_url=//g' | urldecode)"
USER_MAC=$(grep ^$REMOTE_HOST </proc/net/arp \
	 | awk 'BEGIN { FS = " " } ; { print $4 }')

# check if user is already splashed; splash otherwise
lockSplash
ISSPLASHED=0
config_load splash_users
is_mac() {
   config_get mac "$1" mac
   if [ "$mac" == "$USER_MAC" ]; then
   	ISSPLASHED=1
   fi
}
config_foreach is_mac user
if [ $ISSPLASHED -eq 0 ]; then
    # user is now free to go
    chain=$chain_prefix$chain_id
    iptables -t nat -I $chain 1 -m mac --mac-source $USER_MAC -j ACCEPT

    uci -q add splash_users user >/dev/null
    uci -q set splash_users.@user[-1].mac=$USER_MAC
    uci -q set splash_users.@user[-1].time=`date +%s`
fi

# send response (encode / to not confuse sed)
sed "s/targeturl/$(echo "$URL" | sed 's#/#\\/#g')/g" iframe.html
