#!/bin/sh
echo -en "Status: 200 OK\r\n"
echo -en "Content-Type: text/html\r\n"
echo -en "\r\n"
TEST=`cat `
TEST=`echo $TEST | sed 's/'target_url='/''/g'`
TEST=`/bin/urldecode "$TEST"`
TEST=`echo $TEST | sed 's/%2F/\//g'`
. $IPKG_INSTROOT/etc/functions.sh
ISSPLASHED=0
config_load splash_users
is_ip() {
   config_get ip "$1" ip
   if [ "$ip" == "$REMOTE_HOST" ]; then
   	ISSPLASHED=1
   fi
}
#check if user is alredy splashed
config_foreach is_ip user
sed 's/targeturl/'"$(echo $TEST| sed 's#/#\\/#g')"'/g' /www/iframe.html

if [ $ISSPLASHED -eq 1 ]; then
	exit
fi
#User is now free to go
iptables  -t nat -I ffj_splash 1 -s $REMOTE_HOST -j ACCEPT

uci add splash_users user
uci set splash_users.@user[-1].ip=$REMOTE_HOST
uci set splash_users.@user[-1].time=`date +%s`

exit 0


                                               

