#!/bin/sh
#
# Copyright (C) 2011 OpenWrt.org
# Modified for Freifunk Rheinland

[ -e /etc/config/network ] && exit 0

touch /etc/config/network

. /lib/functions/uci-defaults.sh
. /lib/functions/ff-defaults.sh
. /lib/ar71xx.sh

ucidef_set_interface_loopback

#Create the wlan network (to set the MTU)
ffdef_set_interface_wlan "wlan0-1"

#Create the lan network without interfaces
ucidef_set_interface_lan ""

board=$(ar71xx_board_name)

case "$board" in
all0258n)
	ffdef_set_interface_mesh "eth0 eth1"
	;;

db120)
	ucidef_set_interface_wan "eth0"
	ffdef_set_interface_mesh "eth1"
	ucidef_add_switch "switch0" "1" "1"
	ucidef_add_switch_vlan "switch0" "1" "0 1 2 3 4"
	;;

dir-825-b1|\
tew-673gru)
	ucidef_set_interface_wan "eth1"
	ffdef_set_interface_mesh "eth0.1"
	ucidef_add_switch "rtl8366s" "1" "1"
	ucidef_add_switch_vlan "rtl8366s" "1" "0 1 2 3 5t"
	;;

nbg460n_550n_550nh)
	ucidef_set_interface_wan "eth1"
	ffdef_set_interface_mesh "eth0"
	ucidef_add_switch "rtl8366s" "1" "1"
	ucidef_add_switch_vlan "rtl8366s" "0" "0 1 2 3 5"
	;;

rb-433 |\
rb-433u)
	ucidef_set_interface_wan "eth0"
	ffdef_set_interface_mesh "eth1"
	ucidef_add_switch "switch0" "1" "1"
	ucidef_add_switch_vlan "switch0" "1" "1 2 5"
	;;

rb-450)
	ucidef_set_interface_wan "eth0"
	ffdef_set_interface_mesh "eth1"
	ucidef_add_switch "eth1" "1" "1"
	ucidef_add_switch_vlan "eth1" "1" "0 1 2 3 5"
	;;

rb-450g |\
routerstation-pro)
	ucidef_set_interface_wan "eth0"
	ffdef_set_interface_mesh "eth1"
	ucidef_add_switch "switch0" "1" "1"
	ucidef_add_switch_vlan "switch0" "1" "0 1 2 3 4"
	;;

rb-493g)
	ucidef_set_interface_wan "eth1.2"
	ffdef_set_interface_mesh "eth0 eth1.1"
	ucidef_add_switch "switch0" "1" "1"
	ucidef_add_switch_vlan "switch0" "1" "0 1 2 3 4"
	ucidef_add_switch "switch1" "1" "1"
	ucidef_add_switch_vlan "switch1" "1" "0t 1 2 3 4"
	ucidef_add_switch_vlan "switch1" "2" "0t 5"
	;;

wzr-hp-g300nh2 |\
pb92 |\
ap113)
	ucidef_set_interface_wan "eth0.2"
	ffdef_set_interface_mesh "eth0.1"
	ucidef_add_switch "eth0" "1" "1"
	ucidef_add_switch_vlan "eth0" "1" "0t 1 3 4 5"
	ucidef_add_switch_vlan "eth0" "2" "0t 2"
	;;

tl-wr1043nd)
	ucidef_set_interface_wan "eth0.2"
	ffdef_set_interface_mesh "eth0.1"
	ucidef_add_switch "rtl8366rb" "1" "1"
	ucidef_add_switch_vlan "rtl8366rb" "1" "1 2 3 4 5t"
	ucidef_add_switch_vlan "rtl8366rb" "2" "0 5t"
	;;

tl-wr2543n)
	ucidef_set_interface_wan "eth0.2"
	ffdef_set_interface_mesh "eth0.1" 
	ucidef_add_switch "switch0" "1" "1"
	ucidef_add_switch_vlan "switch0" "1" "1 2 3 4 9t"
	ucidef_add_switch_vlan "switch0" "2" "0 9t"
	;;

tl-wr841n-v1|\
tl-wr941nd)
	ucidef_set_interface_raw "eth" "eth0"
	ucidef_set_interface_wan "wan"
	ffdef_set_interface_mesh "lan1 lan2 lan3 lan4"
	;;

wrt160nl)
	ucidef_set_interface_wan "eth1"
	ffdef_set_interface_mesh "eth0"
	ucidef_add_switch "eth0" "1" "1"
	ucidef_add_switch_vlan "eth0" "1" "0 1 2 3 4 5"
	;;

wzr-hp-g300nh)
	ucidef_set_interface_wan "eth1"
	ffdef_set_interface_mesh "eth0.1"
	ucidef_add_switch "switch0" "1" "1"
	ucidef_add_switch_vlan "switch0" "1" "0 1 2 3 5t"
	;;

aw-nr580 |\
bullet-m |\
eap7660d |\
rb-411 |\
tl-mr11u |\
tl-mr3020 |\
tl-wa901nd |\
tl-wa901nd-v2 |\
tl-wr703n |\
wp543)
	ffdef_set_interface_mesh "eth0"
	;;

alfa-ap96 |\
alfa-nx |\
ap83 |\
jwap003 |\
pb42 |\
pb44 |\
routerstation|\
wpe72)
	ucidef_set_interface_wan "eth0"
	ffdef_set_interface_mesh "eth1"
	;;

ap121 |\
ap121-mini |\
ap96 |\
airrouter |\
dir-600-a1 |\
dir-615-c1 |\
dir-615-e4 |\
ja76pf |\
rb-750 |\
tew-632brp |\
tl-mr3220 |\
tl-mr3420 |\
tl-wr741nd |\
tl-wr741nd-v4 |\
tl-wr841n-v7 |\
whr-g301n |\
whr-hp-g300n |\
whr-hp-gn |\
wzr-hp-ag300h)
	ucidef_set_interface_wan "eth1"
	ffdef_set_interface_mesh "eth0"
	ucidef_add_switch "eth0" "1" "1"
	ucidef_add_switch_vlan "eth0" "1" "0 1 2 3 4"
	;;

wzr-hp-g450h)
	ucidef_set_interface_wan "eth0.2"
	ffdef_set_interface_mesh "eth0.1"
	ucidef_add_switch "eth0" "1" "1"
	ucidef_add_switch_vlan "eth0" "1" "0t 2 3 4 5"
	ucidef_add_switch_vlan "eth0" "2" "0t 1"
	;;

*)
	ucidef_set_interface_wan "eth1"
	ffdef_set_interface_mesh "eth0"
	;;
esac

uci commit network

exit 0
