#!/bin/sh
#
# freifunk - configures a Freifunk Rheinland router
# Copyright (C) 2012  Philipp Psurek <phip@vmail.me>
#
# This program is free software: you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation, either version 3 of the License, or (at your option) any later
# version.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program.  If not, see <http://www.gnu.org/licenses/>.

version(){
echo "Freifunk Version 0.0.20120413"

cat << EOF
Copyright © 2012 Philipp Psurek <phip@vmail.me>
Lizenz GPLv3+: GNU GPL Version 3 oder höher <http://gnu.org/licenses/gpl.html>
Dies ist freie Software: Sie können sie ändern und weitergeben.
Es gibt keinerlei Garantien, soweit wie es das Gesetz erlaubt.
EOF
}

usage(){
cat << EOF
Aufruf: freifunk <Befehl> [<Argument>]
        freifunk <Option>

Befehle:
  set               setzt ein Argument
  list              listet die verfügbaren 

Argumente:
  com <code>        Freifunkzelle
  latlong           Knotenkoordinaten
  static on|n2n|off erweitert die minimale Kompatibilität für statische Knoten
  miniconfig on|off schaltet die Konfiguration über den Webbrowser an oder aus

Optionen:
  -h, --help        Hilfe
  -v, --version     Version

EOF
list_com

cat << EOF

Freifunk manipuliert nur die gängigsten UCI-Befehle und ist kein Ersatz für UCI.
EOF
}

get_case(){
all_case
}

set_case(){
all_case
}

list_case(){
all_case
}

all_case(){
case "$comcase" in
  com)
    comconfig
    exit 0
    ;;
  hostname)
    hostnameconfig
    exit 0
    ;;
  latlong)
    latlongconfig
    exit 0
    ;;
  static)
    static
    exit 0
    ;;
  miniconfig)
    miniconfig
    exit 0
    ;;
  *)
    fehler
    ;;
esac
}

comconfig(){
if [ "$casearg" != "" ] && [ "$command" == "set" ]; then

com=$casearg

# Kanaleinstellung und Senderleistung
uci set wireless.radio0=wifi-device
uci set wireless.radio0.type=${wifitype}
uci set wireless.radio0.channel=$(uci get ff.${com}.channel)
[[ $(uci get wireless.radio0.macaddr 2> /dev/null) != "" ]] \
	&& uci set wireless.radio0.phy= \
	|| uci set wireless.radio0.phy=phy0
uci set wireless.radio0.txpower=20
uci set wireless.radio0.country=${wificountry}
uci set wireless.radio0.disabled=0
#uci show wireless.radio0

# B.A.T.M.A.N.-adv Schnittstelle
uci set wireless.@wifi-iface[0]=wifi-iface
uci set wireless.@wifi-iface[0].device=radio0
uci set wireless.@wifi-iface[0].network=
uci set wireless.@wifi-iface[0].mode=adhoc
uci set wireless.@wifi-iface[0].hidden=0
uci set wireless.@wifi-iface[0].encryption=none
uci set wireless.@wifi-iface[0].ssid="$(uci get ff.${com}.batssid)"
uci set wireless.@wifi-iface[0].bssid="$(uci get ff.${com}.bssid)"
#uci show wireless.@wifi-iface[0]

# Accesspoint SSID
[[ "$(uci get wireless.@wifi-iface[1] 2>/dev/null)" == "wifi-iface" ]] || \
	uci add wireless wifi-iface >/dev/null 2>&1
uci set wireless.@wifi-iface[1]=wifi-iface
uci set wireless.@wifi-iface[1].device=radio0
uci set wireless.@wifi-iface[1].network=mesh
uci set wireless.@wifi-iface[1].mode=ap
uci set wireless.@wifi-iface[1].encryption=none
uci set wireless.@wifi-iface[1].wmm=0
uci set wireless.@wifi-iface[1].ssid=www.freifunk-rheinland.net
#uci show wireless.@wifi-iface[1]

	# Weitere SSIDs
	ssid2="$(uci get ff.${com}.ssid2 2>/dev/null)"
	if [[ "${ssid2}" == "" ]]; then
		uci delete wireless.@wifi-iface[2] 2> /dev/null
	else
		[[ "$(uci get wireless.@wifi-iface[2] 2>/dev/null)" == "wifi-iface" ]] || \
			uci add wireless wifi-iface >/dev/null 2>&1

		uci set wireless.@wifi-iface[2]=wifi-iface
		uci set wireless.@wifi-iface[2].device=radio0
		uci set wireless.@wifi-iface[2].network=mesh
		uci set wireless.@wifi-iface[2].mode=ap
		uci set wireless.@wifi-iface[2].encryption=none
		uci set wireless.@wifi-iface[2].wmm=0
		uci set wireless.@wifi-iface[2].ssid="${ssid2}"
		#uci show wireless.@wifi-iface[2]
	fi

	# Auswahl der richtigen B.A.T.M.A.N.-Schnittstelle
	if [ "${wifitype}" == "atheros" ]; then
		[[ "$(uci get network.wlan.ifname 2> /dev/null)" != "${wifiif}0" ]] \
		&& uci set network.wlan=interface \
		&& uci set network.wlan.ifname=${wifiif}0 \
		&& uci set network.wlan.mtu=1528 \
		&& uci commit network.wlan

		[[ "$(uci get batman-adv.bat0.interfaces 2> /dev/null)" != "${wifiif}0" ]] \
		&& uci set batman-adv.bat0.interfaces=${wifiif}0 \
		&& uci commit batman-adv.bat0.interfaces
	elif [[ "${ssid2}" == "" ]]; then
		[[ "$(uci get network.wlan.ifname 2> /dev/null)" != "${wifiif}0-1" ]] \
		&& uci set network.wlan=interface \
		&& uci set network.wlan.ifname=${wifiif}0-1 \
		&& uci set network.wlan.mtu=1528 \
		&& uci commit network.wlan

		[[ "$(uci get batman-adv.bat0.interfaces 2> /dev/null)" != "${wifiif}0-1" ]] \
		&& uci set batman-adv.bat0.interfaces=${wifiif}0-1 \
		&& uci commit batman-adv.bat0.interfaces
	else
		[[ "$(uci get network.wlan.ifname 2> /dev/null)" != "${wifiif}0-2" ]] \
		&& uci set network.wlan=interface \
		&& uci set network.wlan.ifname=${wifiif}0-2 \
		&& uci set network.wlan.mtu=1528 \
		&& uci commit network.wlan

		[[ "$(uci get batman-adv.bat0.interfaces 2> /dev/null)" != "${wifiif}0-2" ]] \
		&& uci set batman-adv.bat0.interfaces=${wifiif}0-2 \
		&& uci commit batman-adv.bat0.interfaces
	fi

# cloud
uci set cloud.cur.net_mesh=$(uci get ff.${com}.subnet)
uci set cloud.cur.net_ip6ula=$(uci get ff.${com}.ip6ula)

# alte n2n löschen
while uci delete n2n.@edge[-1] 2> /dev/null ; do true; done

# neue n2ns anlegen
n2namount=$(uci get ff.$(uci get ff.${com}.n2n).amount)
i=1
while [  $i -le $n2namount ]; do
	let j=i-1
	uci add n2n edge 2>&1 > /dev/null
	uci set n2n.@edge[${j}].ipaddr=1.2.3.4
	uci set n2n.@edge[${j}].supernode=$(uci get ff.$(uci get ff.${com}.n2n).n2n${i})
	uci set n2n.@edge[${j}].port=$(uci get ff.$(uci get ff.${com}.n2n).port${i})
	uci set n2n.@edge[${j}].community=$(uci get ff.${com}.com)${i}
	uci set n2n.@edge[${j}].key=$(uci get ff.${com}.com)${i}
	uci set n2n.@edge[${j}].devname=n2n${i}
	#uci set n2n.@edge[${j}].route=""
	let i=i+1
done

# uci commit ;-)
uci commit cloud
uci commit n2n
uci commit wireless

# n2n bei manuell konfigurierten Knoten deaktivieren
if [ "${wifitype}" == "atheros" ]; then
/etc/init.d/n2n disable
/etc/init.d/n2n stop
fi

elif [ "$casearg" == "" ] && [ "$command" == "get" ]; then
  uci show wireless
  uci show batman-adv
  uci show network.wlan
  uci show cloud.cur
  uci show n2n
elif [ "$casearg" == "" ] && [ "$command" == "list" ]; then
  list_com
else
  fehler
fi
}

list_com(){
echo "Freifunkzellen:"
# Freifunkzellen aus /etc/config/ff auslesen
for com in $(uci get ff.com.com); do
  c=$(echo ${com} | wc -c)
  fill=$(for i in $(seq $((7-$c))); do echo -n ' '; done)
  echo "  ${com} ${fill}           $(uci get ff.${com}.name)"
done
}


hostnameconfig(){
if [ "$casearg" != "" ] && [ "$command" == "set" ]; then
  uci set system.@system[0].hostname=${casearg}
  uci commit system.@system[0].hostname
elif [ "$casearg" == "" ] && [ "$command" == "get" ]; then
  uci get system.@system[0].hostname
  exit 0
elif [ "$casearg" == "" ] && [ "$command" == "list" ]; then
  echo Nichts zum Auflisten.
else
  fehler
fi
}

latlongconfig(){
if [ "$casearg" != "" ] && [ "$command" == "set" ]; then
	if [[ "$(uci get node.info 2> /dev/null)" == "info" ]]; then
		uci set node.info.latlong=${casearg}
	else
		[[ -e /etc/config/node ]] || touch /etc/config/node
		uci set node.info=info
		uci set node.info.latlong=${casearg}
	fi
	uci commit node
elif [ "$casearg" == "" ] && [ "$command" == "get" ]; then
	uci get node.info.latlong
elif [ "$casearg" == "" ] && [ "$command" == "list" ]; then
	echo Nichts zum Auflisten.
else
  fehler
fi
}

# Tweeks für Statische Knoten
static(){
if [ "$casearg" != "" ] && [ "$command" == "set" ]; then

if [ -d /etc/fsm ]; then
  echo "Dieser knoten wird durch eine Zustandsmaschine automatisch konfiguriert. Die manuelle Konfiguration wird tapfer verweigert."
exit 1
fi


# Einstellungen für die Mesh-Brücke
set_meship6_on(){
# prüfen, ob nicht schon eine IPv6 vergeben wurde
if [ "$(uci get network.mesh.ip6addr 2> /dev/null)" == "" ]; then

MACIP6=$(uci get wireless.radio0.macaddr 2> /dev/null \
         | tr ':' ' ' \
         | awk '{print $1$2":"$3$4":"$5$6}')
IP6ula=$(uci get cloud.cur.net_ip6ula 2> /dev/null \
         | egrep -o 'f[c-d][:0-9a-f]*' \
         | sed -e 's/::$/:/')

if $([ "${MACIP6}" != "" ] && [ "${IP6ula}" != "" ]); then
  uci set network.mesh=interface
  uci set network.mesh.ifname=bat0
  uci set network.mesh.type=bridge
  uci set network.mesh.ip6addr=${IP6ula}FFFF:${MACIP6}/64
  uci set network.mesh.proto=static
  #uci set network.mesh.ipaddr=
  #uci set network.mesh.netmask=255.255.0.0
  uci commit network.mesh

  uci set batman-adv.bat0.gw_mode=client
  uci commit batman-adv.bat0.gw_mode
elif [ "${MACIP6}" == "" ]; then
  echo "Dieser Knoten sollte nicht manuell konfiguriert werden."
  exit 1
elif [ "${IP6ula}" == "" ]; then
  echo "Ihre Freifunkzelle hat keinen IPv6 Prefix."
  exit 1
else
  echo "Dieser Knoten kann mit diesem Programm nicht manuell konfiguriert werden."
  exit 1
fi

else
  echo "Die IPv6 wurde schon vergeben." > /proc/self/fd/2
  exit 1
fi
}

set_meshn2n_on(){
if [ -e /etc/init.d/ffrl-n2n ]; then
  /etc/init.d/ffrl-n2n enable
  /etc/init.d/ffrl-n2n start
else
  echo "n2n ist nicht installiert"
  exit 1
fi
}

set_meshn2n_off(){
[ -e /etc/init.d/n2n ] && /etc/init.d/n2n disable 2> /dev/null
[ -e /etc/init.d/n2n ] && /etc/init.d/n2n stop 2> /dev/null
[ -e /etc/init.d/ffrl-n2n ] && /etc/init.d/ffrl-n2n disable 2> /dev/null
[ -e /etc/init.d/ffrl-n2n ] && /etc/init.d/ffrl-n2n stop 2> /dev/null
}

del_mesh_if(){
if [ "$(uci get network.mesh 2> /dev/null)" == "interface" ]; then
uci del network.mesh=interface 2> /dev/zero
uci commit network
fi
}

  case "$casearg" in
    on)
      set_meshn2n_off
      set_meship6_on 
      exit 0
      ;;
    n2n)
      set_meshn2n_on
      set_meship6_on
      exit 0
      ;;
    off)
      del_mesh_if
      set_meshn2n_off
      exit 0
      ;;
    *)
      fehler
      ;;
  esac
elif [ "$casearg" == "" ] && [ "$command" == "get" ]; then
  uci get network.mesh 2> /dev/null
  exit 0
elif [ "$casearg" == "" ] && [ "$command" == "list" ]; then
  echo "
Diese Einstellung ist für statische Knoten wie 
* D-Link DIR-300
* Linksys WRT54G
oder andere, sich nicht automatisch konfigurierende Knoten bestimmt. Hiermit
werden einfachste Einstellungen dauerhaft gesichert.

Optionen:
  on                statische Konfiguration für Knoten in Reichweite einer 
                    bestehenden Freifunk-Wolke einschalten (eindeutige IPv6 ...)

  n2n               +n2n-Gateway zu anderen Knoten in der gleichen Freifunk-
                    Zelle, sie agieren dann als Internet-Gateways für die Nutzer
                    dieses Knotens, dessen Speicher für NAT nicht ausreicht.
                    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                    !!!  Diese Option sollte nur in den äußersten Notfällen  !!!
                    !!!  aktiviert werden, da sie großen Traffic bei anderen !!!
                    !!!  Freifunkern verursacht. Sprich mit ihnen darüber    !!!
                    !!!  __bevor__ Du dies auf diesem Knoten aktivierst.     !!!
                    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
                    Deaktiviere diese Option mit on, sobald sich in Deiner Nähe
                    eine Freifunk-Wolke mit Internetzugang aufgebaut hat.

  off               statische Konfiguration deaktivieren"
  exit 0
else
  fehler
fi
}

# ;-)
vorlage(){
if [ "$casearg" != "" ] && [ "$command" == "set" ]; then
  exit 0
elif [ "$casearg" == "" ] && [ "$command" == "get" ]; then
  exit 0
elif [ "$casearg" == "" ] && [ "$command" == "list" ]; then
  exit 0
else
  fehler
fi
}

# tweek bei nicht vorhandenen Einträgen
setnode2uci(){
if [[ "$(uci get node.$1 2> /dev/null)" == "$1" ]]; then
  return 0
else
  [[ -e /etc/config/node ]] || touch /etc/config/node
  uci set node.$1=$1
fi
}

miniconfig(){
if [ "$casearg" != "" ] && [ "$command" == "set" ]; then
  case "$casearg" in
    on)
      setnode2uci miniconfig
      uci set node.miniconfig.status=
      uci set uhttpd.miniconfig=uhttpd
      uci commit node.miniconfig
      uci commit uhttpd.miniconfig
      /etc/init.d/uhttpd restart
      exit 0
      ;;
    off)
      setnode2uci miniconfig
      uci set node.miniconfig.status=2
      uci set uhttpd.miniconfig=disabled
      uci commit node.miniconfig
      uci commit uhttpd.miniconfig
      #/etc/init.d/uhttpd restart
      kill -s 9 $(ps | grep -e "$(uci get uhttpd.miniconfig.listen_http)" \
      | head -n1 | awk '{printf $1}') #2> /dev/null
      exit 0
      ;;
    *)
      fehler
      ;;
  esac
elif [ "$casearg" == "" ] && [ "$command" == "get" ]; then
  nodestatus=$(uci get node.miniconfig.status)
  httpstatus=$(uci get uhttpd.miniconfig)
  if [ "${httpstatus}" == "disabled" ]; then
    echo "Miniconfig ist aus"
    exit 0
  elif [ "${nodestatus}" == "" ] || [ "${status}" == "0" ]; then
    echo "Miniconfig ist an und wartet auf die Passworteingabe"
    exit 0
  elif [ "${nodestatus}" == "1" ]; then
    echo "Miniconfig ist an und wartet auf die Konfiguration durch den Benutzer"
    exit 0
  elif [ "${nodestatus}" == "1" ]; then
    echo "Miniconfig ist an und wartet auf die Konfiguration durch den Benutzer"
    exit 0
  else
    echo "freifunk: Unbekannter Miniconfig-Zustand"
    exit 1
  fi
elif [ "$casearg" == "" ] && [ "$command" == "list" ]; then
  echo "Optionen:
  on                Miniconfig im Webbrowser einschalten
  off               Miniconfig im Webbrowser ausschalten"
    exit 0
else
  fehler
fi
}

fehler(){
echo "freifunk: unbekannte Eingabe:" $command $comcase $casearg >&2
exit 1
}

# Plattformerkennung
systemtype=$(cat /proc/cpuinfo | grep "system type" | sed -e "s/^.*: //g")

# andere Wireless-Schnittstellen - andere Sitten:
# D-Link DIR-300
if [ "$systemtype" == "Atheros AR2317" ]; then
  wifiif="ath"
  wifitype="atheros"
  wificountry="276"
# TP-LINK und andere
else
  wifiif="wlan"
  wifitype="mac80211"
  wificountry="DE"
fi

# Eingabeverarbeitung
if [ "$1" != "" ]; then
  command=$1
  comcase=$2
  casearg=$3

  case "$command" in
  --help)
    usage
    exit 0
    ;;
  -h)
    usage
    exit 0
    ;;
  --version)
    version
    exit 0
    ;;
  -v)
    version
    exit 0
    ;;
  set)
    set_case
    exit 0
    ;;
  get)
    get_case
    exit 0
    ;;
  list)
    list_case
    exit 0
    ;;
  *)
    fehler
    ;;
  esac
else
  usage
fi

