#!/bin/sh

read url reftrans < /tmp/redirection_target
if [ -x "$reftrans" ]; then
    url="$url$($reftrans "$HTTP_HOST$REQUEST_URI")"
fi
echo -e \
"Cache-Control: no-cache, max-age=0, no-store, must-revalidate\r
Pragma: no-cache\r
Expires: -1\r
Status: 302 Temporary Redirect\r
Location: $url\r
\r"
