#!/bin/sh /etc/rc.common
# Copyright (C) 2008-2011 OpenWrt.org
#      Modified      2012 Freifunk Rheinland

START=90

start_instance() {
	local cfg="$1"

	config_get type "$cfg" TYPE

	case "$type" in
	  edge)
		# Konfigurationseinstellungen holen
		#config_get ipaddr "$cfg" 'ipaddr'
		#[ -n "$ipaddr" ] || return 1
		config_get supernode "$cfg" 'supernode'
		config_get port "$cfg" 'port'
		config_get community "$cfg" 'community'
		config_get key "$cfg" 'key'
		config_get_bool route "$cfg" 'route' '0'
		[ "$route" = "1" ] && args='-r'
		config_get devname "$cfg" devname

		# eine MAC generieren
		wlaniface=$(uci get network.wlan.ifname)
		node_mac=$(ifconfig $wlaniface | grep HWaddr \
			| awk '{print $5}' | tr -d "\n" | cut -c6-)
		mac_random=$(</dev/urandom tr -dc "0-9a-f" | head -c2)

		# ein n2n-Tunnel starten (fe als Prefix)
		/usr/sbin/edge -f $args -a 169.254.0.1 \
			-d $devname -c $community -k $key \
			-m fe:${mac_random}${node_mac} -l ${supernode}:${port}

		# die IP beseitigen
		ifconfig $devname 0.0.0.0

		# B.A.T.M.A.N. Bescheid sagen
		batctl if add $devname
		;;
# We don't need no supernode
#	  supernode)
#		config_get port "$cfg" port
#		[ -n "$port" ] || return 1
#		service_start /usr/sbin/supernode -l $port
#		;;
	esac
}

stop_instance() {
	local cfg="$1"

	config_get type "$cfg" TYPE

	case "$type" in
	  edge)
		service_stop /usr/sbin/edge
		;;
# again: no supernode
#	  supernode)
#		service_stop /usr/sbin/supernode
#		;;
	esac
}

start() {
	config_load 'n2n'
	config_foreach start_instance 'edge'
#	config_foreach start_instance 'superndoe'
}

stop() {
	config_load 'n2n'
	config_foreach stop_instance 'edge'
#	config_foreach stop_instance 'supernode'
}
