#!/bin/sh -e
. ../common.sh

if test_connectivity internet; then
	logger -t fsm "Node is online"
    echo queen
elif cloud_is_online; then
	logger -t fsm "Cloud is online"
    echo drone
else
	logger -t fsm "Cloud is offline"
    echo robinson
fi
