#!/bin/sh
case "${ACTION:-ifup}" in
        ifup)
                gpioctl set 3
        ;;
        ifdown)
                gpioctl dirout 3
                uci set batman-adv.bat0.gw_mode=client
                uci commit batman-adv
        ;;
esac
